double wait time in drop test (#5704)
## Description

_Describe the purpose of and changes within this Pull Request._

The QuicTestNthPacketDrop test hit 

```DataTest.cpp(3006): error: RecvContext.ServerStreamShutdown.WaitTimeout(2000) not true```

but after looking at the logs, it was making fairly steady progress over two seconds, as far as I can tell. I suspect we just randomly tripped across the existing 2 second limit due to bad luck, so doubled the limit, which is not integral to the test itself.

Resolves #5676

## Testing

_Do any existing tests cover this change? Are new tests needed?_

Builds locally.

## Documentation

_Is there any documentation impact for this change?_

N/A.